import { Euler, Vector3 } from "three";

const BlobSetting = {
  fomosphere: {
    material: {
      roughness: 0.44,
      metalness: 0.73,
      envMapIntensity: 0.95,
      clearcoat: 0.13,
      clearcoatRoughness: 1.0,
      transmission: 1.0,
      color: "#ffffff",
      distort: 0.08,
      frequency: 2.77,
      speed: 1.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.6,
      surfaceFrequency: 1.62,
      numberOfWaves: 3.4,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    lights: [
      {
        position: new Vector3(3.87, -3.73, 1.93),
        intensity: 10.0,
        angle: 0.22,
        distance: 20.0,
        penumbra: 1.0,
        decay: 0.0,
        color: "#000FFF",
      },
      {
        position: new Vector3(-2.8, -6.67, 5.73),
        intensity: 1.7,
        angle: 0.31,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.0,
        color: "#FFFF00",
      },
      {
        position: new Vector3(1.33, -0.27, 7.93),
        intensity: 20.0,
        angle: 1.57,
        distance: 8.2,
        penumbra: 0.0,
        decay: 0.0,
        color: "#7600FF",
      },
    ],
    bg: "#75BCC6",
    map: 6,
    ambient: 0,
    geometry: {
      scale: 1,
      rotate: new Euler(-1.33, -0.13, -2),
    },
  },
  disco: {
    material: {
      roughness: 0.0,
      metalness: 0.0,
      envMapIntensity: 0.05,
      clearcoat: 1.0,
      clearcoatRoughness: 0.14,
      transmission: 0.0,
      color: "#ffffff",
      distort: 0.0,
      frequency: 0.06,
      speed: 2.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.1,
      surfaceFrequency: 0.28,
      numberOfWaves: 1.0,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
      fixNormals: true,
    },
    lights: [
      {
        position: new Vector3(-5.0, 0.07, 1.93),
        intensity: 1.27,
        angle: 0.42,
        distance: 8.27,
        penumbra: 1.0,
        decay: 1.0,
        color: "#00FFF8",
      },
      {
        position: new Vector3(-2.73, -6.67, 5.73),
        intensity: 3.0,
        angle: 0.52,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.5,
        color: "#7800FF",
      },
      {
        position: new Vector3(1.2, 2.67, 4.6),
        intensity: 2.0,
        angle: 0.39,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.5,
        color: "#FFFFFF",
      },
    ],
    bg: "#7600F0",
    map: 0,
    ambient: 1,
    geometry: {
      scale: 1.04,
      rotate: new Euler(0, 0, 0),
    },
  },
  twistertoy: {
    material: {
      roughness: 0.74,
      metalness: 1.0,
      envMapIntensity: 1.0,
      clearcoat: 1.0,
      clearcoatRoughness: 0.14,
      transmission: 0.0,
      color: "#FFFFFF",
      distort: 0.0,
      frequency: 3.05,
      speed: 4.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.27,
      surfaceFrequency: 5.0,
      numberOfWaves: 7.2,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
      fixNormals: true,
    },
    lights: [
      {
        position: new Vector3(-5, 0.07, 1.93),
        intensity: 1.27,
        angle: 0.42,
        distance: 8.27,
        penumbra: 1.0,
        decay: 1.0,
        color: "#00FFF8",
      },
      {
        position: new Vector3(-2.73, -6.67, 5.73),
        intensity: 3.0,
        angle: 0.52,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.5,
        color: "#6300FF",
      },
      {
        position: new Vector3(1.2, 2.67, 4.6),
        intensity: 2.0,
        angle: 0.39,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.5,
        color: "#FFFFFF",
      },
    ],
    bg: "#536C9B",
    map: 1,
    ambient: 0.2,
    geometry: {
      scale: 0.9,
      rotate: new Euler(1.27, 3.16, 0.73),
    },
  },
  fungible: {
    material: {
      roughness: 0.3,
      metalness: 0.0,
      envMapIntensity: 1.2,
      clearcoat: 0.0,
      clearcoatRoughness: 1.0,
      transmission: 0.0,
      color: "#FFFFFF",
      distort: 0.22,
      frequency: 0.87,
      speed: 1.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.93,
      surfaceFrequency: 1.0,
      numberOfWaves: 3.13,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    lights: [
      {
        position: new Vector3(0.2, -10, 1.93),
        intensity: 5.0,
        angle: 1.57,
        distance: 20.0,
        penumbra: 1.0,
        decay: 0.0,
        color: "#00FF6A",
      },
      {
        position: new Vector3(-2.73, 10, 5.73),
        intensity: 5.0,
        angle: 1.57,
        distance: 12.27,
        penumbra: 1.0,
        decay: 0.0,
        color: "#6300FF",
      },
      {
        position: new Vector3(1.33, 2.73, 4.53),
        intensity: 0.0,
        angle: 1.57,
        distance: 20.0,
        penumbra: 1.0,
        decay: 1.0,
        color: "#FF00C0",
      },
    ],
    bg: "#8FD8A5",
    map: 7,
    ambient: 0,
    geometry: {
      scale: 1,
      rotate: new Euler(0.27, 0, 0),
    },
  },
  metalness: {
    material: {
      roughness: 0.36,
      metalness: 1.0,
      envMapIntensity: 1.02,
      clearcoat: 1.0,
      clearcoatRoughness: 0.63,
      transmission: 0.0,
      color: "#FFFFFF",
      distort: 0.0,
      frequency: 3.05,
      speed: 4.0,
      gooPoleAmount: 1,
      surfaceDistort: 1.4,
      surfaceFrequency: 1.74,
      numberOfWaves: 12.07,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
      fixNormals: true,
    },
    lights: [
      {
        position: new Vector3(-5, 0.07, 1.93),
        intensity: 1.27,
        angle: 0.42,
        distance: 8.27,
        penumbra: 0.66,
        decay: 1.0,
        color: "#00FFF8",
      },
      {
        position: new Vector3(-2.73, -6.67, 5.73),
        intensity: 3.0,
        angle: 0.52,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.5,
        color: "#6300FF",
      },
      {
        position: new Vector3(1.2, 2.67, 4.6),
        intensity: 2.0,
        angle: 0.39,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.5,
        color: "#FFFFFF",
      },
    ],
    bg: "#371B53",
    map: 2,
    ambient: 0,
    geometry: {
      scale: 1.04,
      rotate: new Euler(0, 3.16, 0),
    },
  },
};

const Titles = Object.keys(BlobSetting);

export { BlobSetting, Titles };
