export const OPTS = {
    blend: 5,
    intensity: 2,
    force: 1.1,
    distortion: 0.4,
    curl: 1.9,
    radius: 0.3,
    swirl: 4,
    pressure: 0.8,
    densityDissipation: 0.96,
    velocityDissipation: 1.0,
    fluidColor: '#000000',
    backgroundColor: 'transparent',
    showBackground: false,
    rainbow: false,
    dyeRes: 512,
    simRes: 128,
} as const;
