export const pages = [
  {
    name: "fomosphere",
    title: "Image 1",
    imagePath: "/assets/01-fomosphere.png",
    imageName:"Fomosphere",
    // position:-8,
  },
  {
    name: "disco",
    title: "Image 2",
    imagePath: "/assets/02-discobrain.png",
    imageName:"Discobrain",
    // position:-4,
  },
  {
    name: "cyberfly",
    title: "Image 3",
    imagePath: "/assets/03-cyberfly.png",
    imageName:"CyberFly",
    // position: 8,
  },
  {
    name: "twistertoy",
    title: "Image 1",
    imagePath: "/assets/04-twistertoy.png",
    imageName:"Twister Toy",
    // position:0,
  },
  {
    name: "fungible",
    title: "Image 2",
    imagePath: "/assets/05-fungible.png",
    imageName:"Fungible",
    // position:4,
  },
  {
    name: "metalness",
    title: "Image 3",
    imagePath: "/assets/06-metalness.png",
    imageName:"Metalness",
    // position:8,
  },
  
    {
    name: "metagum",
    title: "Image 1",
    imagePath: "/assets/07-metagum.png",
    imageName:"Metagun",
    // position: 24,
  },
  {
      name: "firefly",
      title: "Image 2",
      imagePath: "/assets/08-firefly.png",
      imageName:"Firefly",
      // position: -28,
    },
    {  
      name: "slinky",
      title: "Image 3",
      imagePath: "/assets/09-slinky.png",
      imageName:"Slinky",
      // position: -24,
    },
    {
      name: "t1000",
      title: "Image 3",
      imagePath: "/assets/10-t1000.png",
      imageName:"t1000",
      // position: -20,
    },
    {
      name: "genesys",
      title: "Image 3",
      imagePath: "/assets/11-genesys.png",
      imageName:"genesys",
      // position: -16,
    },
    {
      name: "protocool",
      title: "Image 3",
      imagePath: "/assets/12-protocool.png",
      imageName:"Protocool",
      // position: -12,
    },
    {
      name: "liquidity",
      title: "Image 3",
      imagePath: "/assets/13-liquidity.png",
      imageName:"Liquidity",
      // position: -8,
    },
    {
      name: "lips",
      title: "Image 3",
      imagePath: "/assets/14-lipsync.png",
      imageName:"Lipsync",
      // position: -4,
    },
  ,
  
  
];
